### ISSUE TITLE
Mejorar el Header y las paginas Home y Admin

### ISSUE THREAD

**Issue by jaenfigueroa** [Shadowrunner11/rulesAdmin#206]
### 📋 Subtareas

- [x] Cambiar las imagenes jpg y png a webp
- [x] Implementar que el navegador elija entre la mejor opcion de imagen
- [x] Instalar React-lazy-load
- [x] implementar los componentes de la libreria React-lazy-load en el proyecto

### 📂 Documentacion

- [React-lazy-load](https://www.npmjs.com/package/react-lazy-load-image-component)
