### ISSUE TITLE
Plantillas para issues nuevos

### ISSUE THREAD

**Issue by jaenfigueroa** [Shadowrunner11/rulesAdmin#216]
### Descripción del problema

Se necesita implementar plantillas predeterminadas para los issues nuevos, dependiendo del tipo que sean se posicionen correctamente en la tabla de projects.

### Sub tareas

- [x] Investigación y leer documentación
- [x] Implemetar las plantillas para issues
- [x] Documentación en issues
     - #220

### Enlaces de documentación y/o libros que se usaron

- [Acerca de las plantillas de propuestas y solicitudes de extracción](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- [Sintaxis para formularios de incidencias](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [Sintaxis para el modelado de formato de GitHub](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
- [Configurar las plantillas de reporte de problemas para tu repositorio](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
